apiVersion: v1
kind: Service
metadata:
   name: ubuntu-test-service
spec:
  selector:
  app: ubuntu-test-app
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
    type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-test-app
spec:
  selector:
    matchLabels:
      app: ubuntu
    replicas: 5
  template:
    metadata:
      labels:
      app: ubuntu-test-app
    spec:
      containers:
      - name: ubuntu-test-app
        image: 127.0.0.1:9000/ass-0
        imagePullPolicy: IfNotPresent
        ports:
      - containerPort: 5000
